### ISSUE TITLE
New AUX airco, no local connection possible

### ISSUE THREAD

**Issue by Martijndutch** [ArtemVladimirov/broadlinkac2mqtt#14]
Hi Artem,

In one of your posts on the HA forum you mentioned that you could read the packeges from the ACs to find out what's going on. The situation here is as follow:

- I reset the AC, and use the AC Freedom app to connect
- Somehow the Freedom app instructs the AC to connect to WiFi (I guess via a hidden wifi channel?)
- The AC then connects to the WiFi, and established connection to the cloud service. From that moment on, the AC won't respond to anything on the local network. Port 80 is filtered and remains quiet whatever I throw at it. 

I've captured the communication from the AC to the cloud using tcpdump directly on the WiFi access point. You can find the pcap here: https://we.tl/t-NNlcCMe2HO

as you can see, there is absolutly zero communication between Freedom App and the AC once it's connected to the cloud.

I've seen more people having this issue, it seems that in newer FW the local access is disabled.

**Comment by ArtemVladimirov** [comment]
It is very sad that the new air conditioners do not have the possibility of local control. I live in a region where the internet is not very stable. Moreover, I try not to buy devices without local management, because one day the proprietary cloud may simply disappear and all devices will stop working. There are already many such cases
